#!/usr/bin/env python3
#
# Test for preallocate filter
#
# Copyright (c) 2020 Virtuozzo International GmbH.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

import os
import iotests
import random

MiB = 1024 * 1024
GiB = MiB * 1024
disk = os.path.join(iotests.test_dir, 'disk')
overlay = os.path.join(iotests.test_dir, 'overlay')
refdisk = os.path.join(iotests.test_dir, 'refdisk')
racedisk = os.path.join(iotests.test_dir, 'racedisk')
drive_opts = f'node-name=disk,driver={iotests.imgfmt},' \
    f'file.node-name=filter,file.driver=preallocate,' \
    f'file.file.node-name=file,file.file.filename={disk}'


class TestPreallocateBase(iotests.QMPTestCase):
    def setUp(self):
        iotests.qemu_img_create('-f', iotests.imgfmt, disk, str(10 * MiB))

    def tearDown(self):
        try:
            self.check_small()
            check = iotests.qemu_img_check(disk)
            self.assertFalse('leaks' in check)
            self.assertFalse('corruptions' in check)
            self.assertEqual(check['check-errors'], 0)
        finally:
            os.remove(disk)

    def check_big(self):
        self.assertTrue(os.path.getsize(disk) > 100 * MiB)

    def check_small(self):
        self.assertTrue(os.path.getsize(disk) < 10 * MiB)


class TestQemuImg(TestPreallocateBase):
    def test_qemu_img(self):
        p = iotests.QemuIoInteractive('--image-opts', drive_opts)

        p.cmd('write 0 1M')
        p.cmd('flush')

        self.check_big()

        p.close()


class TestPreallocateFilter(TestPreallocateBase):
    def setUp(self):
        super().setUp()
        self.vm = iotests.VM().add_drive(path=None, opts=drive_opts)
        self.vm.launch()

    def tearDown(self):
        self.vm.shutdown()
        super().tearDown()

    def test_prealloc(self):
        self.vm.hmp_qemu_io('drive0', 'write 0 1M')
        self.check_big()

    def test_external_snapshot(self):
        self.test_prealloc()

        self.vm.cmd('blockdev-snapshot-sync', node_name='disk',
                    snapshot_file=overlay,
                    snapshot_node_name='overlay')

        # on reopen to  r-o base preallocation should be dropped
        self.check_small()

        self.vm.hmp_qemu_io('drive0', 'write 1M 1M')

        self.vm.cmd('block-commit', device='overlay')
        self.complete_and_wait()

        # commit of new megabyte should trigger preallocation
        self.check_big()

    def test_reopen_opts(self):
        self.vm.cmd('blockdev-reopen', options=[{
            'node-name': 'disk',
            'driver': iotests.imgfmt,
            'file': {
                'node-name': 'filter',
                'driver': 'preallocate',
                'prealloc-size': 20 * MiB,
                'prealloc-align': 5 * MiB,
                'file': {
                    'node-name': 'file',
                    'driver': 'file',
                    'filename': disk
                }
            }
        }])

        self.vm.hmp_qemu_io('drive0', 'write 0 1M')
        self.assertTrue(os.path.getsize(disk) == 25 * MiB)


class TestTruncate(iotests.QMPTestCase):
    def setUp(self):
        iotests.qemu_img_create('-f', iotests.imgfmt, disk, str(10 * MiB))
        iotests.qemu_img_create('-f', iotests.imgfmt, refdisk, str(10 * MiB))

    def tearDown(self):
        os.remove(disk)
        os.remove(refdisk)

    def do_test(self, prealloc_mode, new_size):
        iotests.qemu_io('--image-opts', '-c', 'write 0 10M', '-c',
                        f'truncate -m {prealloc_mode} {new_size}',
                        drive_opts)

        iotests.qemu_io('-f', iotests.imgfmt, '-c', 'write 0 10M',
                        '-c', f'truncate -m {prealloc_mode} {new_size}',
                        refdisk)

        stat = os.stat(disk)
        refstat = os.stat(refdisk)

        # The preallocate filter may keep cluster alignment when shrinking,
        # so ignore small differences
        self.assertLess(abs(stat.st_size - refstat.st_size), 64 * 1024)

        # Preallocate filter may leak some internal clusters (for example, if
        # guest write far over EOF, skipping some clusters - they will remain
        # fallocated, preallocate filter don't care about such leaks, it drops
        # only trailing preallocation.
        self.assertLess(abs(stat.st_blocks - refstat.st_blocks) * 512,
                        1024 * 1024)

    def test_real_shrink(self):
        self.do_test('off', '5M')

    def test_truncate_inside_preallocated_area__falloc(self):
        self.do_test('falloc', '50M')

    def test_truncate_inside_preallocated_area__metadata(self):
        self.do_test('metadata', '50M')

    def test_truncate_inside_preallocated_area__full(self):
        self.do_test('full', '50M')

    def test_truncate_inside_preallocated_area__off(self):
        self.do_test('off', '50M')

    def test_truncate_over_preallocated_area__falloc(self):
        self.do_test('falloc', '150M')

    def test_truncate_over_preallocated_area__metadata(self):
        self.do_test('metadata', '150M')

    def test_truncate_over_preallocated_area__full(self):
        self.do_test('full', '150M')

    def test_truncate_over_preallocated_area__off(self):
        self.do_test('off', '150M')


class TestPreallocAsyncWrites(iotests.QMPTestCase):
    def setUp(self):
        # Make sure we get reproducible write patterns on each run
        random.seed(42)
        iotests.qemu_img_create('-f', iotests.imgfmt, disk, '-o',
                                f'cluster_size={MiB},lazy_refcounts=on',
                                str(64 * GiB))

    def tearDown(self):
        os.remove(disk)

    def test_prealloc_async_writes(self):
        def gen_write_pattern():
            n = 0
            while True:
                yield '-P 0xaa' if n else '-z'
                n = 1 - n

        def gen_read_pattern():
            n = 0
            while True:
                yield '-P 0xaa' if n else '-P 0x00'
                n = 1 - n

        requests = 2048 # Number of write/read requests to feed to qemu-io
        total_clusters = 64 * 1024 # 64G / 1M

        wpgen = gen_write_pattern()
        rpgen = gen_read_pattern()

        offsets = random.sample(range(0, total_clusters), requests)
        aio_write_cmds = [f'aio_write {next(wpgen)} {off}M 1M' for off in offsets]
        read_cmds = [f'read {next(rpgen)} {off}M 1M' for off in offsets]

        proc = iotests.QemuIoInteractive('--aio', 'native', '--nocache',
                                         '--image-opts', drive_opts)
        for cmd in aio_write_cmds:
            proc.cmd(cmd)
        proc.close()

        proc = iotests.QemuIoInteractive('-f', iotests.imgfmt, disk)
        for cmd in read_cmds:
            out = proc.cmd(cmd)
            self.assertFalse('Pattern verification failed' in str(out))
        proc.close()


class TestPreallocateRaces(iotests.QMPTestCase):
    # blkdebug under the filter holds the preallocation before it is tracked.
    opts = f'driver=preallocate,prealloc-align=65536,prealloc-size=262144,' \
        f'file.driver=blkdebug,file.image.driver=file,' \
        f'file.image.filename={racedisk}'

    def setUp(self):
        self.proc = None
        with open(racedisk, 'wb') as f:
            f.truncate(MiB)

    def tearDown(self):
        if self.proc:
            self.proc.close()
        os.remove(racedisk)

    def qemu_io(self, *args):
        self.proc = iotests.QemuIoInteractive('-g', *args, '--image-opts',
                                              self.opts)
        return self.proc

    def test_write_below_preallocation(self):
        proc = self.qemu_io('--object', 'iothread,id=t0')
        proc.cmd('break pwritev_zero_untracked prealloc')
        proc.cmd('aio_write -q -t t0 -P 0xaa 1M 64k')
        proc.cmd('wait_break prealloc')

        # Returns while the preallocation is parked only if it never waited.
        out = proc.cmd('write -P 0xcc 4k 4k')

        proc.cmd('resume prealloc')
        proc.cmd('aio_flush')
        self.assertIn('wrote 4096/4096', str(out))

    def test_write_into_preallocation(self):
        proc = self.qemu_io('--object', 'iothread,id=t0',
                            '--object', 'iothread,id=t1')
        proc.cmd('break pwritev_zero_untracked prealloc')
        proc.cmd('aio_write -q -t t0 -P 0xaa 1M 64k')
        proc.cmd('wait_break prealloc')
        proc.cmd('break pwritev late')
        proc.cmd('aio_write -q -t t1 -P 0xbb 1152k 64k')

        # A held-back write never finishes; ask whether it got past the filter.
        late = proc.cmd('resume late')

        proc.cmd('remove_break late')
        proc.cmd('resume prealloc')
        proc.cmd('aio_flush')
        data = proc.cmd('read -P 0xbb 1152k 64k')

        self.assertIn('Could not resume request', str(late))
        self.assertNotIn('Pattern verification failed', str(data))

    def test_write_zeroes_over_written_data(self):
        proc = self.qemu_io()
        proc.cmd('write -q -z 1M 128k')
        proc.cmd('write -q -P 0xaa 1M 64k')
        proc.cmd('write -q -z 1M 256k')
        out = proc.cmd('read -P 0 1M 64k')
        self.assertNotIn('Pattern verification failed', str(out))


if __name__ == '__main__':
    iotests.main(supported_fmts=['qcow2'], required_fmts=['preallocate'],
                 require_hmp=True)
