/*
 * QEMU target info API (returning native types)
 *
 *  Copyright (c) Linaro
 *
 * SPDX-License-Identifier: GPL-2.0-or-later
 */

#ifndef QEMU_TARGET_INFO_H
#define QEMU_TARGET_INFO_H

typedef struct TargetInfo TargetInfo;

/**
 * target_info:
 *
 * Returns: The TargetInfo structure definition for the selected target.
 */
const TargetInfo *target_info(void);

/**
 * target_name:
 *
 * Returns: Canonical target name (i.e. "i386").
 */
const char *target_name(void);

/**
 * target_long_bits:
 *
 * Returns: number of bits in a long type for this target (i.e. 64).
 */
unsigned target_long_bits(void);

/**
 * target_cpu_type:
 *
 * Returns: target CPU base QOM type name (i.e. TYPE_X86_CPU).
 */
const char *target_cpu_type(void);

/**
 * target_big_endian:
 *
 * Returns: %true if the (default) endianness of the target is big endian,
 *          %false otherwise.
 *
 * Common code should normally never need to know about the endianness of
 * the target, so please do *not* use this function unless you  know very
 * well what you are doing!
 */
bool target_big_endian(void);

/*
 * Exact-target and base-family helpers, generated by
 * scripts/gen-target-info.py from the TARGET_BASE_ARCH of every
 * system target:
 *
 *   bool target_is_<arch>(const TargetInfo *ti);
 *   bool target_<arch>(void);
 *   bool target_is_base_<family>(const TargetInfo *ti);
 *   bool target_base_<family>(void);
 */
#include "target-info-gen.h"

#endif
