#!/usr/bin/env python3
# group: quick
#
# Test the NBD client stale channel discard
#
# Copyright (C) 2026 OVHcloud
#
# SPDX-License-Identifier: GPL-2.0-or-later

import time
import iotests
from iotests import qemu_nbd_popen, qemu_img_create, file_path, log


# estimated duration required by the connect thread to reach a running server
MAX_NBD_HANDSHAKE_DURATION = 0.5
# sleep duration of the connection retry in nbd client
CONNECT_RETRY_DELAY = 1

iotests.script_initialize()
nbd_sock = file_path('nbd-sock', base_dir=iotests.sock_dir)
disk = file_path('disk')
qemu_img_create('-f', iotests.imgfmt, disk, '1M')

with iotests.VM() as vm:

    vm.launch()

    with qemu_nbd_popen('-k', nbd_sock, '-f', iotests.imgfmt, disk):
        vm.cmd('blockdev-add', {
            'driver': 'nbd',
            'node-name': 'nbd0',
            'server': {'type': 'unix', 'path': nbd_sock},
        })
        iotests.log('=== NBD Device connected ===')
        log(vm.qmp('x-qemu-io', device='nbd0', command='write -P 0x5a 0 64k'))

    iotests.log('=== NBD server down. Detect the break and start the connect '
                'thread ===')
    # client was in CONNECTED state a new operation updates to CONNECTING
    log(vm.qmp('x-qemu-io', device='nbd0', command='write -P 0x5a 0 64k'))
    # in CONNECTING, the operation starts the connect thread
    log(vm.qmp('x-qemu-io', device='nbd0', command='write -P 0x5a 0 64k'))

    with qemu_nbd_popen('-k', nbd_sock, '-f', iotests.imgfmt, disk):
        iotests.log('=== NBD server up. Wait for the connect thread to park '
                    'the channel ===')
        # wait for the connect thread to get a new channel and stop
        time.sleep(CONNECT_RETRY_DELAY + MAX_NBD_HANDSHAKE_DURATION)

    iotests.log('=== NBD server down. The parked channel is closed ===')

    with qemu_nbd_popen('-k', nbd_sock, '-f', iotests.imgfmt, disk):
        iotests.log('=== NBD server up. Restart the connect thread ===')
        # operation will determine that the channel got closed and restart the
        # connect thread
        log(vm.qmp('x-qemu-io', device='nbd0', command='write -P 0x5a 0 64k'))
        # Wait for it to succeed
        iotests.log('=== Wait for the connect thread to park the new channel. '
                    'Subsequent operations are successful ===')
        time.sleep(MAX_NBD_HANDSHAKE_DURATION)
        log(vm.qmp('x-qemu-io', device='nbd0', command='write -P 0x5a 0 64k'))
