# SPDX-License-Identifier: GPL-2.0-or-later

"""
trace/generated-tracers.c
"""

__author__     = "Lluís Vilanova <vilanova@ac.upc.edu>"
__copyright__  = "Copyright 2012-2014, Lluís Vilanova <vilanova@ac.upc.edu>"
__license__    = "GPL version 2 or (at your option) any later version"

__maintainer__ = "Stefan Hajnoczi"
__email__      = "stefanha@redhat.com"


from tracetool import out


def generate(events, backend, group):
    header = "trace-" + group + ".h"

    out('/* This file is autogenerated by tracetool, do not edit. */',
        '/* SPDX-License-Identifier: GPL-2.0-or-later */',
        '',
        '#include "qemu/osdep.h"',
        '#include "qemu/module.h"',
        '#include "%s"' % header,
        '')

    if len(list(backend.backend_modules())):
        for e in events:
            out('uint8_t %s;' % e.api(e.QEMU_DSTATE))

        for e in events:
            out('TraceEvent %(event)s = {',
                '#ifdef CONFIG_TRACE_SIMPLE',
                '    .id = 0,',
                '#endif',
                '    .name = \"%(name)s\",',
                '    .dstate = &%(dstate)s',
                '};',
                event = e.api(e.QEMU_EVENT),
                name = e.name,
                dstate = e.api(e.QEMU_DSTATE))

        out('TraceEvent *%(group)s_trace_events[] = {',
            group = group.lower())

        for e in events:
            out('    &%(event)s,', event = e.api(e.QEMU_EVENT))

        out('  NULL,',
            '};',
            '')

        out('static void trace_%(group)s_register_events(void)',
            '{',
            '    trace_event_register_group(%(group)s_trace_events);',
            '}',
            'trace_init(trace_%(group)s_register_events)',
            group = group.lower())

        backend.generate_begin(events, group)
        for event in events:
            backend.generate(event, group)
        backend.generate_end(events, group)
