#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0-or-later
"""Generate TargetInfo target helpers and abstract machine parents.

meson passes every system target with its TARGET_BASE_ARCH, independent
of --target-list, as --target <name>=<base>.  <name> is a SysEmuTarget
member; a target without one fails to compile.

For every target <arch> and every base family <family>:
    bool target_is_<arch>(const TargetInfo *ti);
    bool target_<arch>(void);
    bool target_is_base_<family>(const TargetInfo *ti);
    bool target_base_<family>(void);
    TYPE_TARGET_<ARCH>_MACHINE        "target-<arch>-machine"
    TYPE_TARGET_BASE_<FAMILY>_MACHINE "target-base-<family>-machine"

Machine parents are abstract and only registered when available.
<arch> parents inherit their <family> parent, which inherits TYPE_MACHINE.
"""

import argparse
import os
import re
import sys
from typing import Dict, List

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from qapi.common import c_enum_const, c_name

HEADER = "/* Generated by scripts/gen-target-info.py. Do not edit. */"
C_IDENT = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


def parse_targets(pairs: List[str]) -> Dict[str, List[str]]:
    """Return {family: [target, ...]}, both sorted."""
    seen = set()
    families: Dict[str, List[str]] = {}
    for pair in pairs:
        name, _, family = pair.partition("=")
        if not name or not C_IDENT.match(family) or name in seen:
            sys.exit(f"{sys.argv[0]}: bad or duplicate --target '{pair}'")
        seen.add(name)
        families.setdefault(family, []).append(name)
    return {f: sorted(t) for f, t in sorted(families.items())}


def write(path: str, lines: List[str]) -> None:
    with open(path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join([HEADER, ""] + lines + [""]))


def predicate(fn: str, cases: List[str]) -> List[str]:
    body = (["    switch (ti->target_arch) {"]
            + [f"    case {c}:" for c in cases]
            + ["        return true;", "    default:",
               "        return false;", "    }"])
    return [f"bool target_is_{fn}(const TargetInfo *ti)", "{", *body, "}",
            "", f"bool target_{fn}(void)", "{",
            f"    return target_is_{fn}(target_info());", "}", ""]


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("--target", action="append", required=True,
                        metavar="NAME=TARGET_BASE_ARCH")
    parser.add_argument("outdir")
    args = parser.parse_args()
    families = parse_targets(args.target)

    # (helper suffix, QOM name, enum constants, parent macro or None)
    entries = []
    for family, targets in families.items():
        consts = [c_enum_const("SysEmuTarget", t) for t in targets]
        entries.append((f"base_{family}", f"target-base-{family}",
                        consts, None))
    for family, targets in families.items():
        for t in targets:
            entries.append((c_name(t, False), f"target-{t}",
                            [c_enum_const("SysEmuTarget", t)],
                            f"TYPE_TARGET_BASE_{family.upper()}_MACHINE"))

    def macro(fn: str) -> str:
        return f"TYPE_TARGET_{fn.upper()}_MACHINE"

    header = ["#ifndef TARGET_INFO_GEN_H", "#define TARGET_INFO_GEN_H", "",
              "typedef struct TargetInfo TargetInfo;", ""]
    for fn, _, _, _ in entries:
        header += [f"bool target_is_{fn}(const TargetInfo *ti);",
                   f"bool target_{fn}(void);", ""]
    write(os.path.join(args.outdir, "target-info-gen.h"),
          header + ["#endif"])

    source = []
    for fn, _, consts, _ in entries:
        source += predicate(fn, consts)
    write(os.path.join(args.outdir, "target-info-gen.c.inc"), source)

if __name__ == "__main__":
    main()
