// SPDX-License-Identifier: GPL-2.0-or-later
// This file is @generated by tracetool, do not edit.

#[allow(unused_imports)]
use std::ffi::c_char;
#[allow(unused_imports)]
use util::bindings;

#[allow(dead_code)]
#[inline(always)]
fn trace_event_state_is_enabled(dstate: u8) -> bool {
    (unsafe { trace_events_enabled_count }) != 0 && dstate != 0
}

extern "C" {
    #[allow(dead_code)]
    static mut trace_events_enabled_count: u32;
}
extern "C" {
    #[allow(dead_code)]
    static mut _TRACE_TEST_BLAH_DSTATE: u8;
    #[allow(dead_code)]
    static mut _TRACE_TEST_WIBBLE_DSTATE: u8;
}

use std::cell::UnsafeCell;

extern "C" {
    #[allow(dead_code)]
    static qemu_test_blah_semaphore: UnsafeCell<u16>;
    #[allow(dead_code)]
    static qemu_test_wibble_semaphore: UnsafeCell<u16>;
}

#[inline(always)]
#[allow(dead_code)]
pub fn trace_test_blah_enabled() -> bool
{
    (unsafe {qemu_test_blah_semaphore.get().read_volatile()}) != 0 ||
    trace_event_state_is_enabled(unsafe { _TRACE_TEST_BLAH_DSTATE}) ||
    false
}

#[inline(always)]
#[allow(dead_code)]
pub fn trace_test_blah(_context: *mut (), _filename: &std::ffi::CStr)
{
    ::trace::probe!(qemu, test_blah, _context, _filename.as_ptr());
    if trace_event_state_is_enabled(unsafe { _TRACE_TEST_BLAH_DSTATE}) {
        let format_string = c"Blah context=%p filename=%s";
        unsafe {bindings::ftrace_write(format_string.as_ptr() as *const c_char, _context /* as *mut () */, _filename.as_ptr());}
        let format_string = c"test_blah Blah context=%p filename=%s\n";
        if (unsafe { bindings::qemu_loglevel } & bindings::LOG_TRACE) != 0 {
            unsafe { bindings::qemu_log(format_string.as_ptr() as *const c_char, _context /* as *mut () */, _filename.as_ptr());}
        }
        extern "C" { fn _simple_trace_test_blah(_context: *mut (), _filename: *const std::ffi::c_char); }
        unsafe { _simple_trace_test_blah(_context, _filename.as_ptr()); }
        let format_string = c"Blah context=%p filename=%s";
        unsafe {::trace::syslog(::trace::LOG_INFO, format_string.as_ptr() as *const c_char, _context /* as *mut () */, _filename.as_ptr());}
    }
}

#[inline(always)]
#[allow(dead_code)]
pub fn trace_test_wibble_enabled() -> bool
{
    (unsafe {qemu_test_wibble_semaphore.get().read_volatile()}) != 0 ||
    trace_event_state_is_enabled(unsafe { _TRACE_TEST_WIBBLE_DSTATE}) ||
    false
}

#[inline(always)]
#[allow(dead_code)]
pub fn trace_test_wibble(_context: *mut (), _value: std::ffi::c_int)
{
    ::trace::probe!(qemu, test_wibble, _context, _value);
    if trace_event_state_is_enabled(unsafe { _TRACE_TEST_WIBBLE_DSTATE}) {
        let format_string = c"Wibble context=%p value=%d";
        unsafe {bindings::ftrace_write(format_string.as_ptr() as *const c_char, _context /* as *mut () */, _value /* as std::ffi::c_int */);}
        let format_string = c"test_wibble Wibble context=%p value=%d\n";
        if (unsafe { bindings::qemu_loglevel } & bindings::LOG_TRACE) != 0 {
            unsafe { bindings::qemu_log(format_string.as_ptr() as *const c_char, _context /* as *mut () */, _value /* as std::ffi::c_int */);}
        }
        extern "C" { fn _simple_trace_test_wibble(_context: *mut (), _value: std::ffi::c_int); }
        unsafe { _simple_trace_test_wibble(_context, _value); }
        let format_string = c"Wibble context=%p value=%d";
        unsafe {::trace::syslog(::trace::LOG_INFO, format_string.as_ptr() as *const c_char, _context /* as *mut () */, _value /* as std::ffi::c_int */);}
    }
}

