/* This file is autogenerated by tracetool, do not edit. */
/* SPDX-License-Identifier: GPL-2.0-or-later */

#ifndef TRACE_TESTSUITE_GENERATED_TRACERS_H
#define TRACE_TESTSUITE_GENERATED_TRACERS_H

#include "trace/control.h"

extern TraceEvent _TRACE_TEST_BLAH_EVENT;
extern TraceEvent _TRACE_TEST_WIBBLE_EVENT;
extern uint8_t _TRACE_TEST_BLAH_DSTATE;
extern uint8_t _TRACE_TEST_WIBBLE_DSTATE;
#ifndef SDT_USE_VARIADIC
#define SDT_USE_VARIADIC 1
#endif
#include "trace-dtrace-testsuite.h"

#undef SDT_USE_VARIADIC
#ifndef QEMU_TEST_BLAH_ENABLED
#define QEMU_TEST_BLAH_ENABLED() true
#endif
#ifndef QEMU_TEST_WIBBLE_ENABLED
#define QEMU_TEST_WIBBLE_ENABLED() true
#endif
#include "trace/ftrace.h"

#include "qemu/log-for-trace.h"

void _simple_trace_test_blah(void *context, const char *filename);
void _simple_trace_test_wibble(void *context, int value);

#include <syslog.h>

#include <lttng/tracepoint.h>
#include "trace-ust-testsuite.h"

/* tracepoint_enabled() was introduced in LTTng UST 2.7 */
#ifndef tracepoint_enabled
#define tracepoint_enabled(a, b) true
#endif


#define TRACE_TEST_BLAH_BACKEND_DSTATE() ( \
    QEMU_TEST_BLAH_ENABLED() || \
    (trace_event_get_state_dynamic_by_id(TRACE_TEST_BLAH) && \
     qemu_loglevel_mask(LOG_TRACE)) || \
    tracepoint_enabled(qemu, test_blah) || \
    trace_event_get_state_dynamic_by_id(TRACE_TEST_BLAH) || \
    false)

static inline void trace_test_blah(void *context, const char *filename)
{
    QEMU_TEST_BLAH(context, filename);
    if (trace_event_get_state_dynamic_by_id(TRACE_TEST_BLAH) &&
        qemu_loglevel_mask(LOG_TRACE)) {
#line 4 "trace-events"
            qemu_log("test_blah " "Blah context=%p filename=%s" "\n", context, filename);
#line 59 "all.h"
    }
    tracepoint(qemu, test_blah, context, filename);
    if (trace_event_get_state_dynamic_by_id(TRACE_TEST_BLAH)) {
#line 4 "trace-events"
        ftrace_write("test_blah " "Blah context=%p filename=%s" "\n" , context, filename);
#line 65 "all.h"
        _simple_trace_test_blah(context, filename);
#line 4 "trace-events"
        syslog(LOG_INFO, "test_blah " "Blah context=%p filename=%s" , context, filename);
#line 69 "all.h"
    }
}

#define TRACE_TEST_WIBBLE_BACKEND_DSTATE() ( \
    QEMU_TEST_WIBBLE_ENABLED() || \
    (trace_event_get_state_dynamic_by_id(TRACE_TEST_WIBBLE) && \
     qemu_loglevel_mask(LOG_TRACE)) || \
    tracepoint_enabled(qemu, test_wibble) || \
    trace_event_get_state_dynamic_by_id(TRACE_TEST_WIBBLE) || \
    false)

static inline void trace_test_wibble(void *context, int value)
{
    QEMU_TEST_WIBBLE(context, value);
    if (trace_event_get_state_dynamic_by_id(TRACE_TEST_WIBBLE) &&
        qemu_loglevel_mask(LOG_TRACE)) {
#line 5 "trace-events"
            qemu_log("test_wibble " "Wibble context=%p value=%d" "\n", context, value);
#line 88 "all.h"
    }
    tracepoint(qemu, test_wibble, context, value);
    if (trace_event_get_state_dynamic_by_id(TRACE_TEST_WIBBLE)) {
#line 5 "trace-events"
        ftrace_write("test_wibble " "Wibble context=%p value=%d" "\n" , context, value);
#line 94 "all.h"
        _simple_trace_test_wibble(context, value);
#line 5 "trace-events"
        syslog(LOG_INFO, "test_wibble " "Wibble context=%p value=%d" , context, value);
#line 98 "all.h"
    }
}
#endif /* TRACE_TESTSUITE_GENERATED_TRACERS_H */
