// SPDX-License-Identifier: GPL-2.0-or-later
// This file is @generated by tracetool, do not edit.

#[allow(unused_imports)]
use std::ffi::c_char;
#[allow(unused_imports)]
use util::bindings;

#[allow(dead_code)]
#[inline(always)]
fn trace_event_state_is_enabled(dstate: u8) -> bool {
    (unsafe { trace_events_enabled_count }) != 0 && dstate != 0
}

extern "C" {
    #[allow(dead_code)]
    static mut trace_events_enabled_count: u32;
}
extern "C" {
    #[allow(dead_code)]
    static mut _TRACE_TEST_BLAH_DSTATE: u8;
    #[allow(dead_code)]
    static mut _TRACE_TEST_WIBBLE_DSTATE: u8;
}

#[inline(always)]
#[allow(dead_code)]
pub fn trace_test_blah_enabled() -> bool
{
    false
}

#[inline(always)]
#[allow(dead_code)]
pub fn trace_test_blah(_context: *mut (), _filename: &std::ffi::CStr)
{
}

#[inline(always)]
#[allow(dead_code)]
pub fn trace_test_wibble_enabled() -> bool
{
    false
}

#[inline(always)]
#[allow(dead_code)]
pub fn trace_test_wibble(_context: *mut (), _value: std::ffi::c_int)
{
}

