/* This file is autogenerated by tracetool, do not edit. */
/* SPDX-License-Identifier: GPL-2.0-or-later */

#ifndef TRACE_TESTSUITE_GENERATED_TRACERS_H
#define TRACE_TESTSUITE_GENERATED_TRACERS_H

#include "trace/control.h"

extern TraceEvent _TRACE_TEST_BLAH_EVENT;
extern TraceEvent _TRACE_TEST_WIBBLE_EVENT;
extern uint8_t _TRACE_TEST_BLAH_DSTATE;
extern uint8_t _TRACE_TEST_WIBBLE_DSTATE;
#define TRACE_TEST_BLAH_ENABLED 1
#define TRACE_TEST_WIBBLE_ENABLED 1

#define TRACE_TEST_BLAH_BACKEND_DSTATE() ( \
    false)

static inline void trace_test_blah(void *context, const char *filename)
{
}

#define TRACE_TEST_WIBBLE_BACKEND_DSTATE() ( \
    false)

static inline void trace_test_wibble(void *context, int value)
{
}
#endif /* TRACE_TESTSUITE_GENERATED_TRACERS_H */
